# Generated by Django 5.1 on 2024-09-28 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_epi'),
    ]

    operations = [
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_devolucao', models.DateField()),
                ('data_emprestimo', models.DateField()),
                ('motivo_devolução', models.CharField(max_length=100)),
                ('id_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='EPIgenerico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('prazo_dias', models.CharField(max_length=100)),
                ('id_lista_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='listaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCargo_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cargo')),
                ('id_epigenerico_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.epigenerico')),
            ],
        ),
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoque', models.IntegerField()),
                ('data_validade', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='EPI',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='id_ficha_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.epigenerico'),
        ),
        migrations.AddField(
            model_name='produto',
            name='id_emprestimo_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.emprestimo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='id_epigenerico_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.epigenerico'),
        ),
    ]
