# Generated by Django 5.1 on 2024-10-16 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cargo_emprestimo_epigenerico_listaepi_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='condicoes',
            field=models.CharField(db_default='', max_length=100),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_prevista',
            field=models.DateField(db_default='00/00/00'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='status',
            field=models.IntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(db_default='00/00/00'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(db_default='00/00/00'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='id_ficha_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listaepi'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='motivo_devolução',
            field=models.TextField(db_default='00/00/00'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='nome',
            field=models.CharField(db_default='', max_length=100),
        ),
    ]
