# Generated by Django 5.1 on 2024-10-16 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_emprestimo_condicoes_emprestimo_data_prevista_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='id_ficha_fk',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='id_usuario_fk',
        ),
        migrations.RemoveField(
            model_name='epigenerico',
            name='id_lista_fk',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='id_EPIgenerico_fk',
            field=models.ForeignKey(db_default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.epigenerico'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.TextField(db_default=''),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(db_default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(db_default=''),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(db_default=''),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista',
            field=models.DateField(db_default=''),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='motivo_devolução',
            field=models.TextField(db_default=''),
        ),
        migrations.DeleteModel(
            name='listaEPI',
        ),
    ]
