# Generated by Django 5.1 on 2024-10-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(db_default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(db_default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista',
            field=models.DateField(db_default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='motivo_devolução',
            field=models.TextField(db_default='2020-01-01'),
        ),
    ]
